CREATE TYPE session_status AS ENUM ('UPLOADING', 'GENERATING_PLAN', 'EDITING_PLAN', 'CHUNKING', 'ACTIVE', 'COMPLETED');
CREATE TYPE processing_status AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED');
CREATE TYPE chat_type AS ENUM ('TOPIC_SPECIFIC', 'GENERAL_REVIEW');
CREATE TYPE chunk_type AS ENUM ('problem', 'theory');
